const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log('Languages Array:');
console.log(languages);
var firstElement = languages[0];
console.log('First Element: ' + firstElement);
var thirdElement = languages[2];
console.log('Third Element: ' + thirdElement);
var length = languages.length;
console.log('Array Length: ' + length);
var lastElement = length - 1;
console.log('Last in Array: ' + languages[lastElement]);
